// <auto-generated />
using BackendDemo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendDemo.Migrations
{
    [DbContext(typeof(BackendDemoContext))]
    [Migration("20210531015928_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("BackendDemo.Domain.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "descripcion producto 1",
                            Nombre = "Producto1"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "descripcion producto 2",
                            Nombre = "Producto2"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "descripcion producto 3",
                            Nombre = "Producto3"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "descripcion producto 4",
                            Nombre = "Producto4"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "descripcion producto 5",
                            Nombre = "Producto5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
